name: Ubuntu-Server
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: Download Script
         run: |
           git clone https://github.com/cloudcdh/vsocks5
           
        - name: Compile The  Docker Container
          
        run: |
          cd source || exit 1
          docker container prune --force || true
          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t socks5
          docker image ls
      - name: running Docker
        timeout-minutes: 340
        continue-on-error: true
        run: |
          docker run --privileged --rm -i socks5
           
